name: 'Field Group Settings'
type: module
description: Provides a field group display formatter for hiding settings.
package : Fields
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - field_group:field_group
