field_group_settings.field_group_formatter_plugin.settings:
  type: field_group.field_group_formatter_plugin.base
  label: 'Mapping for the settings formatter settings'
  mapping:
    visible_for_roles:
      type: sequence
      label: 'Roles that may view'
      sequence:
        type: string